"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = true

[palette]
black = '#262B44'
blue = '#4B95E9'
green = '#59C9A5'
orange = '#F07623'
red = '#D81E5B'
white = '#FFFFFF'
yellow = '#F3AE35'
light_yellow = '#FfbF46'
purple = '#8899EE'

[[blocks]]
type = "prompt"
alignment = "left"
leading_diamond = ""
trailing_diamond = ""
[[blocks.segments]]
type = 'status'
foreground = "p:white"
style = 'diamond'
background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
# leading_diamond = '<transparent,background>󱞪</>'
# template = ' {{ if gt .Code 0 }}{{ else }}{{ end }}'
template = "{{ if eq .Code 0 }}\uf00c{{ else }}\uf071 {{ reason .Code }}{{ end }} "
[[blocks.segments]]
type = "git"
style = "diamond"
foreground = "p:white"
background_templates = [
	"{{ if or (.Working.Changed) (.Staging.Changed) }}p:blue{{ end }}",
	"{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:light_yellow{{ end }}",
	"{{ if gt .Ahead 0 }}p:purple{{ end }}",
	"{{ if gt .Behind 0 }}p:green{{ end }}",
]
template = " {{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
background = "p:blue"
[blocks.segments.properties]
fetch_status = true
fetch_upstream_icon = true
[[blocks.segments]]
type = "rust"
style = "diamond"
background = "p:black"
foreground = "p:white"
template = " 󱘗 {{ .Full }} "
[[blocks.segments]]
type = "path"
background = "p:purple"
foreground = "p:white"
template = "  {{if .Segments.Git.Ref}}{{.Segments.Git.RepoName}}{{.Path | replace .Segments.Git.Dir \"\"}}{{else}}{{.Path}}{{end}} "
style = "diamond"
[blocks.segments.properties]
style = "full"
[blocks.segments.properties.mapped_locations]
"~/Documents/Uni" = " "
"~/Music" = " "
"~/Projects/" = " "
"~/BuildFromSource/" = "󰘬"
"~/.config" = "󰣖 "


[[blocks]]
type = "prompt"
alignment = "left"
newline = true
force = true
[[blocks.segments]]
type = "text"
foreground = "p:green"
style = "plain"
template = "  󱞪"


[[blocks]]
type = "rprompt"
[[blocks.segments]]
style = "plain"
type = "executiontime"

[transient_prompt]
background = "transparent"
foreground = "#ffffff"
template = "{{if gt .Code 0 }}<p:red></><p:white,p:red>\uf071 {{reason .Code}} </>{{else}}<p:purple,transparent></>{{end}}<p:white,p:purple>  {{ .PWD }} </><p:purple,transparent></> "
# template = "\uE0b6 {{ .UserName }} \uE0B0"
